version: "3.5"

services:

  web:
    image: node:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1g
      placement:
        constraints:
          - node.hostname == network-disk
    ports:
      - target: 3000
        published: 9001
        protocol: tcp
        mode: host
    volumes:
      - ../:/data
    networks:
      - deploy
    command: sh -c 'cd /data && yarn && yarn run prod'

networks:
  deploy:
